# Generated by Django 5.0.7 on 2024-08-02 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Q',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('제목', models.CharField(max_length=100)),
                ('보기A', models.CharField(max_length=100)),
                ('보기B', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BG.q'),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
