# Generated by Django 5.0.7 on 2024-08-02 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BG', '0002_q_alter_comment_article_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Q_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('답변', models.CharField(max_length=100)),
                ('내용', models.TextField()),
                ('Q_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BG.q')),
            ],
        ),
    ]
